In [60]:
from bk import bk
import pandas as pd
import dataframe_image as dfi
from slugify import slugify
from pathlib import Path

overview = pd.DataFrame()
overview.name='Monatliche Kosten im Verlgeich'

def df_style(val):
    return "font-weight: bold; background-color: yellow"

In [61]:
cars = [{'label': 'BMW 3er Maximus',
         'car_price': 16903,
         'car_year': 2011,
         'interest_rate': 0.,
         'rest_value': 1500,
         'insurance': 775,
         'taxes': 230,
         'consumption': 6.38,
         'fuel_price': 1.19,
         'repairs': 2016.32,
         'millage': 26000,
         'holding': 6.85,
         'image_url': 'cars/bmw-3er-maximus.png',
         'web_url': 'https://de.wikipedia.org/wiki/BMW_E90'
        }]
cars.append({'label': 'Mercedes C 220d T',
             'car_price': 28890,
             'car_year': 2019,
             'interest_rate': 3.,
             'rest_value': 5000,
             'insurance': 775,
             'taxes': 230,
             'consumption': 6.,
             'fuel_price': 1.65,
             'repairs': 1800,
             'millage': 18000,
             'holding': 6.0,  
             'image_url': 'cars/mercedes-c-220d-t.png',
             'web_url': 'https://suchen.mobile.de/fahrzeuge/details.html?action=parkItem&id=336723447'
})
cars.append({'label': 'Mercedes C 200 T',
             'car_price': 29970,
             'car_year': 2019,
             'interest_rate': 3.,
             'rest_value': 7000,
             'insurance': 775,
             'taxes': 136,
             'consumption': 8.,
             'fuel_price': 1.85,
             'repairs': 900,
             'millage': 18000,
             'holding': 6.0,  
             'image_url': 'cars/mercedes-c-200-t.png',
             'web_url': 'https://suchen.mobile.de/fahrzeuge/details.html?action=parkItem&id=327113608'
})
cars.append({'label': 'Tesla Model Y',
             'car_price': 51000,
             'car_year': 2022,
             'interest_rate': 3.,
             'rest_value': 5000,
             'insurance': 775,
             'taxes': 0,
             'consumption': 16.,
             'fuel_price': .3,
             'repairs': 500,
             'millage': 18000,
             'holding': 10.0,   
             'image_url': 'cars/tesla-model-y.jpg',
             'web_url': 'https://www.tesla.com/de_de/modely/design#overview'
})
cars.append({'label': 'Mazda 6 neu',
             'car_price': 29692,
             'car_year': 2022,
             'interest_rate': 3.,
             'rest_value': 3000,
             'insurance': 775,
             'taxes': 136,
             'consumption': 8.,
             'fuel_price': 2.00,
             'repairs': 900,
             'millage': 18000,
             'holding': 10.0,  
             'image_url': 'cars/mazda-6-neu.png',
             'web_url': 'https://konfigurator.meinauto.de/mazda/neuwagen/48-6/angebote/6-kombi/konfigurator/#!/extras/exclusive-line/8846370/10,11/private/65352-5416-204698/984/61c9aa657e74c/cash-purchase/32545--287374/48,0,10000,0,0,0,0,0,'
})
cars.append({'label': 'Kia ceed SW',
             'car_price': 26992.36,
             'car_year': 2022,
             'interest_rate': 3.,
             'rest_value': 3000,
             'insurance': 775,
             'taxes': 136,
             'consumption': 7.,
             'fuel_price': 2.00,
             'repairs': 900,
             'millage': 18000,
             'holding': 10.0,
             'image_url': 'cars/kia-ceed-sportswagon.png',
             'web_url': 'https://konfigurator.meinauto.de/kia/neuwagen/cee-d/angebote/cee-d-sporty-wagon/konfigurator/#!/preisvergleich/platinum/8867329/3,7,18/private/109347-4167-291321/1321/61d21ce73c5db/cash-purchase/109348-8088-291322/48,0,10000,0,0,0,0,0,'
})
cars.append({'label': 'Mazda 6 alt',
             'car_price': 22980,
             'car_year': 2017,
             'interest_rate': 3.,
             'rest_value': 4000,
             'insurance': 775,
             'taxes': 136,
             'consumption': 8.,
             'fuel_price': 1.85,
             'repairs': 900,
             'millage': 18000,
             'holding': 4.0,  
             'image_url': 'cars/mazda-6-alt.png',
             'web_url': 'https://suchen.mobile.de/fahrzeuge/details.html?action=parkItem&id=332186075'
})
#cars

In [62]:
latex = ''
for car in cars:
    label=car['label']
    (input_values, calc_values) = bk(car['car_price'],
                                     car['insurance'],
                                     car['taxes'],
                                     car['consumption'],
                                     car['fuel_price'],
                                     car['repairs'],
                                     car['millage'],
                                     car['holding'],
                                     label=label,
                                     interest_rate=car['interest_rate'],
                                     rest_value=car['rest_value'])
    
    input_values_path = 'images/' + slugify(label) + '-boundaries.png'
    calc_df_path = 'images/' + slugify(label) + '-calc_df.png'
    
    latex = r"""%s
\twocolumn

\section*{%s}
\begin{center}
\includegraphics[width=0.9\columnwidth]{%s}
\null
\vspace{0.5cm}
\includegraphics[width=0.9\columnwidth]{%s}
\end{center}

\pagebreak
\null
\vspace{2cm}
\begin{center}
\includegraphics[width=0.9\columnwidth]{%s}

%s, %d, Laufzeit: %.0f Jahre, \href{%s}{Weblink}
\end{center}

\pagebreak

""" %(latex,
      label,
      input_values_path,
      calc_df_path,
      car['image_url'],
      label,
      car['car_year'],
      car['holding'],
      car['web_url'].replace('#', '\#')
     )

    overview[label] = calc_values['Monatlich']
    
    
    sum_row = pd.IndexSlice[calc_values.index[calc_values.index == "SUMME"], :]
    dfi.export(input_values.round(2), input_values_path)
    dfi.export(calc_values.style.applymap(df_style, subset=sum_row).set_precision(2), calc_df_path)

<ipython-input-62-70a8902ba9c5>:57: FutureWarning: this method is deprecated in favour of `Styler.format(precision=..)`
  dfi.export(calc_values.style.applymap(df_style, subset=sum_row).set_precision(2), calc_df_path)

In [63]:
display(overview.round(2))

overview_path = 'images/overview.png'

sum_row = pd.IndexSlice[calc_values.index[calc_values.index == "SUMME"], :]
dfi.export(overview.style.applymap(df_style, subset=sum_row).set_precision(2), overview_path)
latex = r"""%s

\pagebreak

\onecolumn
\null
\vfill 
\begin{center}
\includegraphics[width=0.95\columnwidth]{%s}
\end{center}
\vfill 
""" % (latex,
      overview_path)

,BMW 3er Maximus,Mercedes C 220d T,Mercedes C 200 T,Tesla Model Y,Mazda 6 neu,Kia ceed SW,Mazda 6 alt
Anschaffungskosten,205.63,401.25,416.25,425.00,247.43,224.94,478.75
Zinsen,0.00,37.70,39.10,67.46,39.27,35.70,29.90
Versicherung,64.58,64.58,64.58,64.58,64.58,64.58,64.58
Steuern,19.17,19.17,11.33,0.00,11.33,11.33,11.33
Reparaturen,168.03,150.00,75.00,41.67,75.00,75.00,75.00
Verbrauch,164.50,148.50,222.00,72.00,240.00,210.00,222.00
SUMME,621.91,821.20,828.27,670.71,677.62,621.56,881.56
Restwert,-18.25,-69.44,-97.22,-41.67,-25.00,-25.00,-83.33
Summe mit Restwert,603.66,751.75,731.05,629.04,652.62,596.56,798.23

<ipython-input-63-d76031242fdb>:6: FutureWarning: this method is deprecated in favour of `Styler.format(precision=..)`
  dfi.export(overview.style.applymap(df_style, subset=sum_row).set_precision(2), overview_path)

In [64]:
with open('report.tex', 'w') as fid:
    fid.write(r"""
\documentclass[landscape, DIV=99, 14pt]{scrartcl}

\renewcommand*{\familydefault}{\sfdefault}

\RequirePackage{graphicx}
\RequirePackage{hyperref}

\begin{document}

\twocolumn
\includegraphics[width=1.1\columnwidth]{images/kosten_verteilung.png}
\includegraphics[width=1.4\columnwidth]{images/kosten_maximus.png}

\pagebreak

\begin{itemize}
    \item Wertverlust
    \begin{itemize}
        \item Kaufpreis minus Verkaufspreis
        \item Kraftstoffe
        \item Summe aller Tankstellenbesuche
    \end{itemize}
    \item Wartung und Reparatur
    \begin{itemize}
        \item Regul\"are Wartungsarbeiten (\"Olwechsel, etc)
        \item Reparaturen Aufgrund technischer Defekte
        \item Unfallsch\"aden
    \end{itemize}
    \item Versicherung
    \begin{itemize}
        \item J\"ahrlicher Versicherungsbeitrag
        \item Mobilit\"ats-Service
    \end{itemize}
    \item Steuern
    \begin{itemize}
            \item J\"ahrliche KFZ-Steuer
    \end{itemize}
\end{itemize}

%s

\end{document}
""" % (latex))