In [1]:
from bk import bk
import pandas as pd
import dataframe_image as dfi
from slugify import slugify
from pathlib import Path

overview = pd.DataFrame()
overview.name='Monatliche Kosten im Verlgeich'

def df_style(val):
    return "font-weight: bold; background-color: yellow"

In [2]:
d_0 = 1.52  # Aktueller Dieselpreis 3.1.2022: 1.52
b_0 = 1.56  # Aktueller Benzinpreis 3.1.2022: 1.56
e_0 = 0.31  # Aktueller Strompreis 3.1.2022: 0.31 €/kWh

d_6 = 1.65  # Durschnittlicher Dieselpreis geschätzt bis 2028

b_5 = 1.75  # Durschnittlicher Benzinpreis geschätzt bis 2027
b_6 = 1.80  # Durschnittlicher Benzinpreis geschätzt bis 2028
b_10 = 2.0  # Durschnittlicher Benzinpreis geschätzt bis 2032

e_10 = 0.30 # Durschnittlicher Strompreis geschätzt bis 2032

cars = [{'label': 'BMW 318d 2011',
         'acquisition_cost': 16903,
         'car_year': 2011,
         'delivery_time': 0,
         'interest_rate': 0.,
         'rest_value': 3000,
         'insurance_yearly': 775,
         'taxes_yearly': 230,
         'consumption': 6.38,
         'power': 137,
         'fuel_price': 1.19,  # Durchschnittlicher Dieselpreis seit 2015
         'fuel_type': 'Diesel',
         'repairs_yearly': 2016.32,
         'millage_yearly': 26000,
         'holding_period': 6.85,
         'image_url': 'cars/bmw-3er-maximus.png',
         'web_url': 'https://de.wikipedia.org/wiki/BMW_E90'
        }]
cars.append({'label': 'Nissan Micra 2010',
             'acquisition_cost': 3300,
             'car_year': 2011,
             'delivery_time': 0,
             'interest_rate': 0.,
             'rest_value': 2000,
             'insurance_yearly': 361.76,
             'taxes_yearly': 64,
             'consumption': 6.6,
             'power': 65,
             'fuel_price': 1.36,  # Durchschnittlicher Dieselpreis seit 2016
             'fuel_type': 'Benzin',
             'repairs_yearly': 395.40,
             'millage_yearly': 3216,
             'holding_period': 5.5,  
             'image_url': 'cars/nissan-micra.jpg',
             'web_url': 'https://de.wikipedia.org/wiki/Nissan_Micra#Micra_(K12,_2003%E2%80%932010)'
})
cars.append({'label': 'Mercedes C 220d',
             'acquisition_cost': 28890,
             'car_year': 2019,
             'delivery_time': 0,
             'interest_rate': 3.,
             'rest_value': 5000,
             'insurance_yearly': 775,
             'taxes_yearly': 230,
             'consumption': 6.,
             'power': 194,
             'fuel_price': d_6,
             'fuel_type': 'Diesel',
             'repairs_yearly': 1800,
             'millage_yearly': 18000,
             'holding_period': 6.0,  
             'image_url': 'cars/mercedes-c-220d-t.png',
             'web_url': 'https://suchen.mobile.de/fahrzeuge/details.html?action=parkItem&id=336723447'
})
cars.append({'label': 'Mercedes C 200',
             'acquisition_cost': 29970,
             'car_year': 2019,
             'delivery_time': 0,
             'interest_rate': 3.,
             'rest_value': 7000,
             'insurance_yearly': 545.79,
             'taxes_yearly': 136,
             'consumption': 8.,
             'power': 184,
             'fuel_price': b_6,
             'fuel_type': 'Benzin',
             'repairs_yearly': 900,
             'millage_yearly': 18000,
             'holding_period': 6.0,  
             'image_url': 'cars/mercedes-c-200-t.png',
             'web_url': 'https://suchen.mobile.de/fahrzeuge/details.html?action=parkItem&id=327113608'
})
cars.append({'label': 'Mercedes C 180',
             'acquisition_cost': 42755.83,
             'car_year': 2022,
             'delivery_time': 60,
             'interest_rate': 3.,
             'rest_value': 7000,
             'insurance_yearly': 678.24,
             'taxes_yearly': 136,
             'consumption': 7.,
             'power': 170,
             'fuel_price': b_10,
             'fuel_type': 'Benzin',
             'repairs_yearly': 900,
             'millage_yearly': 18000,
             'holding_period': 10.0,  
             'image_url': 'cars/mercedes-c-180-t.png',
             'web_url': 'https://konfigurator.meinauto.de/mercedes/neuwagen/c-klasse/angebote/c-klasse-t-modell/konfigurator/#!/preisvergleich/-/8866563/2,47,74,81/private/43735-7309-290394/349/61d36ce4c3067/cash-purchase/73169--190162/48,0,10000,0,0,0,0,0,'
})             
cars.append({'label': 'Tesla Model Y',
             'acquisition_cost': 51000,
             'car_year': 2022,
             'delivery_time': 8,
             'interest_rate': 3.,
             'rest_value': 5000,
             'insurance_yearly': 541.02,
             'taxes_yearly': 0,
             'consumption': 16.,
             'power': 345,
             'fuel_price': e_10,
             'fuel_type': 'Strom',
             'repairs_yearly': 500,
             'millage_yearly': 18000,
             'holding_period': 10.0,   
             'image_url': 'cars/tesla-model-y.jpg',
             'web_url': 'https://www.tesla.com/de_de/modely/design#overview'
})
cars.append({'label': 'Mazda 6 geb.',
             'acquisition_cost': 22980,
             'car_year': 2017,
             'delivery_time': 0,
             'interest_rate': 3.,
             'rest_value': 3000,
             'insurance_yearly': 691.51,
             'taxes_yearly': 136,
             'consumption': 8.,
             'power': 192,
             'fuel_price': b_5,
             'fuel_type': 'Benzin',
             'repairs_yearly': 900,
             'millage_yearly': 18000,
             'holding_period': 5.0,  
             'image_url': 'cars/mazda-6-alt.png',
             'web_url': 'https://suchen.mobile.de/fahrzeuge/details.html?action=parkItem&id=332186075'
})
cars.append({'label': 'Mazda 6 neu',
             'acquisition_cost': 29692,
             'car_year': 2022,
             'delivery_time': 60,
             'interest_rate': 3.,
             'rest_value': 3000,
             'insurance_yearly': 601.16,
             'taxes_yearly': 136,
             'consumption': 8.,
             'power': 192,
             'fuel_price': b_10,
             'fuel_type': 'Benzin',
             'repairs_yearly': 900,
             'millage_yearly': 18000,
             'holding_period': 10.0,  
             'image_url': 'cars/mazda-6-neu.png',
             'web_url': 'https://konfigurator.meinauto.de/mazda/neuwagen/48-6/angebote/6-kombi/konfigurator/#!/extras/exclusive-line/8846370/10,11/private/65352-5416-204698/984/61c9aa657e74c/cash-purchase/32545--287374/48,0,10000,0,0,0,0,0,'
})
cars.append({'label': 'Kia ceed',
             'acquisition_cost': 26992.36,
             'car_year': 2022,
             'delivery_time': 52,
             'interest_rate': 3.,
             'rest_value': 3000,
             'insurance_yearly': 381.08,
             'taxes_yearly': 136,
             'consumption': 7.,
             'power': 160,
             'fuel_price': b_10,
             'fuel_type': 'Benzin',
             'repairs_yearly': 900,
             'millage_yearly': 18000,
             'holding_period': 10.0,
             'image_url': 'cars/kia-ceed-sportswagon.png',
             'web_url': 'https://konfigurator.meinauto.de/kia/neuwagen/cee-d/angebote/cee-d-sporty-wagon/konfigurator/#!/preisvergleich/platinum/8867329/3,7,18/private/109347-4167-291321/1321/61d21ce73c5db/cash-purchase/109348-8088-291322/48,0,10000,0,0,0,0,0,'
})
cars.append({'label': 'Skoda Superb',
             'acquisition_cost': 26890,
             'car_year': 2019,
             'delivery_time': 0,
             'interest_rate': 3.,
             'rest_value': 8000,
             'insurance_yearly': 601.26,
             'taxes_yearly': 230,
             'consumption': 6.5,
             'power': 190,
             'fuel_price': d_6,
             'fuel_type': 'Diesel',
             'repairs_yearly': 1200,
             'millage_yearly': 18000,
             'holding_period': 6.0,
             'image_url': 'cars/skoda-superb.png',
             'web_url': 'https://suchen.mobile.de/fahrzeuge/details.html?id=336967099'
})
cars.append({'label': 'Skoda Octavia',
             'acquisition_cost': 16250,
             'car_year': 2019,
             'delivery_time': 0,
             'interest_rate': 3.,
             'rest_value': 4000,
             'insurance_yearly': 458.92,
             'taxes_yearly': 230,
             'consumption': 6.0,
             'power': 150,
             'fuel_price': d_6,
             'fuel_type': 'Diesel',
             'repairs_yearly': 1200,
             'millage_yearly': 18000,
             'holding_period': 6.0,
             'image_url': 'cars/skoda-octavia.png',
             'web_url': 'https://suchen.mobile.de/fahrzeuge/details.html?id=333524150'
})
cars.append({'label': 'BMW Gran Tourer',
             'acquisition_cost': 28990,
             'car_year': 2019,
             'delivery_time': 0,
             'interest_rate': 3.,
             'rest_value': 7000,
             'insurance_yearly': 586.82,
             'taxes_yearly': 130,
             'consumption': 8.21,
             'power': 192,
             'fuel_price': b_6,
             'fuel_type': 'Benzin',
             'repairs_yearly': 900,
             'millage_yearly': 18000,
             'holding_period': 6.0,
             'image_url': 'cars/bmw-gran-tourer.png',
             'web_url': 'https://suchen.mobile.de/fahrzeuge/details.html?id=336851737'
})
cars.append({'label': 'Skoda Kodiaq 2.0 TSI',
             'acquisition_cost': 29950,
             'car_year': 2019,
             'delivery_time': 0,
             'interest_rate': 3.,
             'rest_value': 7000,
             'insurance_yearly': 479.25,
             'taxes_yearly': 130,
             'consumption': 9.24,
             'power': 190,
             'fuel_price': b_6,
             'fuel_type': 'Benzin',
             'repairs_yearly': 900,
             'millage_yearly': 18000,
             'holding_period': 6.0,
             'image_url': 'cars/skoda-kodiaq-2p0-tsi.png',
             'web_url': 'https://suchen.mobile.de/fahrzeuge/details.html?id=336695573'
})
cars.append({'label': 'Skoda Kodiaq 2.0 TDI',
             'acquisition_cost': 34890,
             'car_year': 2019,
             'delivery_time': 0,
             'interest_rate': 3.,
             'rest_value': 7000,
             'insurance_yearly': 486.05,
             'taxes_yearly': 230,
             'consumption': 7.95,
             'power': 190,
             'fuel_price': d_6,
             'fuel_type': 'Diesel',
             'repairs_yearly': 1200,
             'millage_yearly': 18000,
             'holding_period': 6.0,
             'image_url': 'cars/skoda-kodiaq-2p0-tdi.png',
             'web_url': 'https://suchen.mobile.de/fahrzeuge/details.html?id=319879014'
})
cars.append({'label': 'Fiat Tipo',
             'acquisition_cost': 14900,
             'car_year': 2019,
             'delivery_time': 0,
             'interest_rate': 3.,
             'rest_value': 3000,
             'insurance_yearly': 487.10,
             'taxes_yearly': 100,
             'consumption': 8.13,
             'power': 120,
             'fuel_price': b_6,
             'fuel_type': 'Benzin',
             'repairs_yearly': 1200,
             'millage_yearly': 18000,
             'holding_period': 6.0,
             'image_url': 'cars/fiat-tipo.png',
             'web_url': 'https://suchen.mobile.de/fahrzeuge/details.html?id=333199596'
})
cars.append({'label': 'VW Passat',
             'acquisition_cost': 22980,
             'car_year': 2018,
             'delivery_time': 0,
             'interest_rate': 3.,
             'rest_value': 6000,
             'insurance_yearly': 522.14,
             'taxes_yearly': 146,
             'consumption': 8.48,
             'power': 220,
             'fuel_price': b_5,
             'fuel_type': 'Benzin',
             'repairs_yearly': 1200,
             'millage_yearly': 18000,
             'holding_period': 5.0,
             'image_url': 'cars/vw-passat.png',
             'web_url': 'https://www.autohus.de/autosuche/details/260323/vw-passat-var-2-0-tsi/'
})

#cars

# Use formula to calculate restvalue:
# for idx, _ in enumerate(cars):
#     print(cars[idx]['label'], 'estimated rest value:', cars[idx]['rest_value'])
#     cars[idx]['rest_value'] = cars[idx]['acquisition_cost'] * .5**(cars[idx]['holding_period']/3)
#     print('Rule of thumb rest value: %.0f' % cars[idx]['rest_value'], '\n')

In [3]:
latex = ''
for car in cars:
    label=car['label']
    bk_inputs = a_subset = {key: car[key] for key in ['acquisition_cost', 
                                                      'holding_period',
                                                      'millage_yearly',
                                                      'consumption',
                                                      'fuel_price',
                                                      'repairs_yearly',  # bis hierher Hauptkosten
                                                      'interest_rate',
                                                      'taxes_yearly',
                                                      'insurance_yearly',
                                                      'rest_value']}
    (input_values, calc_values) = bk(**bk_inputs)
    
    input_values_path = Path('images/' + slugify(label) + '-boundaries.png')
    calc_df_path = Path('images/' + slugify(label) + '-calc_df.png')
    
    latex = r"""%s
\twocolumn

\section*{%s}
\begin{center}
\includegraphics[width=0.9\columnwidth]{%s}
\null
\vspace{0.5cm}
\includegraphics[width=0.9\columnwidth]{%s}
\end{center}

\pagebreak
\null
\vspace{2cm}
\begin{center}
\includegraphics[width=0.9\columnwidth]{%s}

%s
\end{center}

\begin{itemize}
    \item Baujahr: %d $\rightarrow$ Laufzeit: %.0f Jahre
    \item \href{%s}{Weblink}
    \item \emph{Gesch\"atzter} Spritpreis \"uber Haltedauer: %.2f \euro{}/l
    \item Antrieb: %s, mit %d PS
\end{itemize}

\pagebreak

""" %(latex,
      label,
      input_values_path.as_posix(),
      calc_df_path.as_posix(),
      car['image_url'],
      label,
      car['car_year'],
      car['holding_period'],
      car['web_url'].replace('#', '\#'),
      car['fuel_price'],
      car['fuel_type'],
      car['power']
     )

    # calc_values.loc['Lieferzeit', :] = car['delivery_time']
    # calc_values.loc['Kraftstoffsorte', :] = car['fuel_type']
    # calc_values = calc_values.reindex(index = ['Lieferzeit',
    #                                            'Kraftstoffsorte',
    #                                            'Anschaffungskosten',
    #                                            'Zinsen',
    #                                            'Versicherung',
    #                                            'Steuern',
    #                                            'Reparaturen',
    #                                            'Verbrauch',
    #                                            'SUMME',
    #                                            'Restwert',
    #                                            'Summe mit Restwert'
    #                                           ])
    
    overview[label] = calc_values['Monatlich']
    
    input_values_path.parent.mkdir(parents=True, exist_ok=True)
    
    sum_row = pd.IndexSlice[calc_values.index[calc_values.index == "SUMME"], :]
    dfi.export(input_values.round(2), str(input_values_path))
    dfi.export(calc_values.style.applymap(df_style, subset=sum_row).set_precision(2), str(calc_df_path))
    #display(input_values.round(2))
    #display(calc_values.style.applymap(df_style, subset=sum_row).set_precision(2))

<ipython-input-3-2ee26cda0102>:83: FutureWarning: this method is deprecated in favour of `Styler.format(precision=..)`
  dfi.export(calc_values.style.applymap(df_style, subset=sum_row).set_precision(2), str(calc_df_path))

In [6]:
brk = 8

overview_path_1 = 'images/overview1.png'
overview_path_2 = 'images/overview2.png'

sum_row = pd.IndexSlice[calc_values.index[calc_values.index == "SUMME"], :]

dfi.export(overview.iloc[:, 0:brk ].style.applymap(df_style, subset=sum_row).set_precision(2), overview_path_1)
dfi.export(overview.iloc[:, brk: ].style.applymap(df_style, subset=sum_row).set_precision(2), overview_path_2)

display(overview.iloc[:, 0:brk ].style.applymap(df_style, subset=sum_row).set_precision(2))
display(overview.iloc[:, brk: ].style.applymap(df_style, subset=sum_row).set_precision(2))

latex = r"""%s

\pagebreak

\onecolumn
\null
\vfill 
\begin{center}
\includegraphics[width=0.95\columnwidth]{%s}
\null
\vspace{0.5cm}
\includegraphics[width=0.95\columnwidth]{%s}
\end{center}
\vfill 
""" % (latex,
      overview_path_1,
      overview_path_2)

<ipython-input-6-b89f13b0144d>:8: FutureWarning: this method is deprecated in favour of `Styler.format(precision=..)`
  dfi.export(overview.iloc[:, 0:brk ].style.applymap(df_style, subset=sum_row).set_precision(2), overview_path_1)
<ipython-input-6-b89f13b0144d>:9: FutureWarning: this method is deprecated in favour of `Styler.format(precision=..)`
  dfi.export(overview.iloc[:, brk: ].style.applymap(df_style, subset=sum_row).set_precision(2), overview_path_2)
<ipython-input-6-b89f13b0144d>:11: FutureWarning: this method is deprecated in favour of `Styler.format(precision=..)`
  display(overview.iloc[:, 0:brk ].style.applymap(df_style, subset=sum_row).set_precision(2))

<ipython-input-6-b89f13b0144d>:12: FutureWarning: this method is deprecated in favour of `Styler.format(precision=..)`
  display(overview.iloc[:, brk: ].style.applymap(df_style, subset=sum_row).set_precision(2))

In [5]:
with open('report.tex', 'w') as fid:
    fid.write(r"""
\documentclass[landscape, DIV=99, 14pt]{scrartcl}

\renewcommand*{\familydefault}{\sfdefault}

\RequirePackage{graphicx}
\RequirePackage{hyperref}
\RequirePackage[gen]{eurosym}

\begin{document}

\twocolumn
\section*{Zusammenfassung BMW Kosten}
\includegraphics[width=1.1\columnwidth, trim=0 0 0 2cm]{images/kosten_verteilung.png}
\includegraphics[width=1.4\columnwidth]{images/kosten_maximus.png}

\pagebreak

\begin{itemize}
    \item Wertverlust
    \begin{itemize}
        \item Kaufpreis minus Verkaufspreis
        \item Kraftstoffe
        \item Summe aller Tankstellenbesuche
    \end{itemize}
    \item Wartung und Reparatur
    \begin{itemize}
        \item Regul\"are Wartungsarbeiten (\"Olwechsel, etc)
        \item Reparaturen Aufgrund technischer Defekte
        \item Unfallsch\"aden
    \end{itemize}
    \item Versicherung
    \begin{itemize}
        \item J\"ahrlicher Versicherungsbeitrag
        \item Mobilit\"ats-Service
    \end{itemize}
    \item Steuern
    \begin{itemize}
            \item J\"ahrliche KFZ-Steuer
    \end{itemize}
\end{itemize}

%s

\end{document}
""" % (latex))